/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_SignatureProtect_SignatureJni */

#ifndef _Included_com_example_SignatureProtect_SignatureJni
#define _Included_com_example_SignatureProtect_SignatureJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_SignatureProtect_SignatureJni
 * Method:    isEqual
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_signatureprotect_SignatureJni_isEqual
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
